In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC



In [10]:
from sklearn.svm import SVR

In [18]:
iris=datasets.load_iris()

In [19]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [29]:
x=iris.data

In [32]:
y=iris.target

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)   

In [34]:
len(x_train)

105

In [35]:
len(x_test)

45

In [36]:
model=SVC()
model.fit(x_train,y_train)

SVC()

In [37]:
model.score(x_test,y_test)

0.9777777777777777

In [38]:
y_pred=model.predict(x_test)

In [39]:
y_pred

array([0, 1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 2,
       2, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       1])

In [40]:
from sklearn.metrics import confusion_matrix

In [42]:
cm=confusion_matrix(y_test,y_pred)

In [43]:
cm

array([[16,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 14]], dtype=int64)

In [44]:
len(y_test)

45

In [48]:
accuracy=(cm[0][0]+cm[1][1]+cm[2][2])/len(y_test)

In [49]:
accuracy

0.9777777777777777

In [57]:
C=1.0
svc=SVC(kernel='linear',C=1,gamma='auto')

In [58]:
svc.fit(x_train,y_train)

SVC(C=1, gamma='auto', kernel='linear')

In [61]:
svc.score(x_test,y_test)

0.9777777777777777

In [62]:
cm=confusion_matrix(y_test,y_pred)

In [63]:
print(cm)

[[16  0  0]
 [ 0 14  1]
 [ 0  0 14]]


In [64]:
accuracy=(cm[0][0]+cm[1][1]+cm[2][2])/len(y_test)

In [65]:
accuracy

0.9777777777777777

In [66]:
C=1.0
svc=SVC(kernel='rbf',C=1,gamma='auto')

In [67]:
svc.fit(x_train,y_train)

SVC(C=1, gamma='auto')

In [68]:
svc.score(x_test,y_test)

0.9777777777777777