In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv("project3train.csv")

In [3]:
test=pd.read_csv("project3test.csv")

In [4]:
test.head()

id state  account_length      area_code international_plan voice_mail_plan  \
0   1    KS             128  area_code_415                 no             yes   
1   2    AL             118  area_code_510                yes              no   
2   3    IA              62  area_code_415                 no              no   
3   4    VT              93  area_code_510                 no              no   
4   5    NE             174  area_code_415                 no              no   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     25              265.1              110   
1                      0              223.4               98   
2                      0              120.7               70   
3                      0              190.7              114   
4                      0              124.3               76   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             45.07              197.4               99             16.78   
1             37.98              220.6              101             18.75   
2             20.52              307.2               76             26.11   
3             32.42              218.2              111             18.55   
4             21.13              277.1              112             23.55   

   total_night_minutes  total_night_calls  total_night_charge  \
0                244.7                 91               11.01   
1                203.9                118                9.18   
2                203.0                 99                9.14   
3                129.6                121                5.83   
4                250.7                115               11.28   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                10.0                 3               2.70   
1                 6.3                 6               1.70   
2                13.1                 6               3.54   
3                 8.1                 3               2.19   
4                15.5                 5               4.19   

   number_customer_service_calls  
0                              1  
1                              0  
2                              4  
3                              3  
4                              3

In [5]:
train.head()

state  account_length      area_code international_plan voice_mail_plan  \
0    OH             107  area_code_415                 no             yes   
1    NJ             137  area_code_415                 no              no   
2    OH              84  area_code_408                yes              no   
3    OK              75  area_code_415                yes              no   
4    MA             121  area_code_510                 no             yes   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     26              161.6              123   
1                      0              243.4              114   
2                      0              299.4               71   
3                      0              166.7              113   
4                     24              218.2               88   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             27.47              195.5              103             16.62   
1             41.38              121.2              110             10.30   
2             50.90               61.9               88              5.26   
3             28.34              148.3              122             12.61   
4             37.09              348.5              108             29.62   

   total_night_minutes  total_night_calls  total_night_charge  \
0                254.4                103               11.45   
1                162.6                104                7.32   
2                196.9                 89                8.86   
3                186.9                121                8.41   
4                212.6                118                9.57   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                13.7                 3               3.70   
1                12.2                 5               3.29   
2                 6.6                 7               1.78   
3                10.1                 3               2.73   
4                 7.5                 7               2.03   

   number_customer_service_calls churn  
0                              1    no  
1                              0    no  
2                              2    no  
3                              3    no  
4                              3    no

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
train["state"]=le.fit_transform(train["state"])

In [9]:
train["area_code"]=le.fit_transform(train["area_code"])

In [10]:
varlist=['international_plan','voice_mail_plan','churn']

In [11]:
train

state  account_length  area_code international_plan voice_mail_plan  \
0        35             107          1                 no             yes   
1        31             137          1                 no              no   
2        35              84          0                yes              no   
3        36              75          1                yes              no   
4        19             121          2                 no             yes   
...     ...             ...        ...                ...             ...   
4245     26              83          1                 no              no   
4246     49              73          0                 no              no   
4247     27              75          0                 no              no   
4248     11              50          0                 no             yes   
4249     46              86          1                 no             yes   

      number_vmail_messages  total_day_minutes  total_day_calls  \
0                        26              161.6              123   
1                         0              243.4              114   
2                         0              299.4               71   
3                         0              166.7              113   
4                        24              218.2               88   
...                     ...                ...              ...   
4245                      0              188.3               70   
4246                      0              177.9               89   
4247                      0              170.7              101   
4248                     40              235.7              127   
4249                     34              129.4              102   

      total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0                27.47              195.5              103             16.62   
1                41.38              121.2              110             10.30   
2                50.90               61.9               88              5.26   
3                28.34              148.3              122             12.61   
4                37.09              348.5              108             29.62   
...                ...                ...              ...               ...   
4245             32.01              243.8               88             20.72   
4246             30.24              131.2               82             11.15   
4247             29.02              193.1              126             16.41   
4248             40.07              223.0              126             18.96   
4249             22.00              267.1              104             22.70   

      total_night_minutes  total_night_calls  total_night_charge  \
0                   254.4                103               11.45   
1                   162.6                104                7.32   
2                   196.9                 89                8.86   
3                   186.9                121                8.41   
4                   212.6                118                9.57   
...                   ...                ...                 ...   
4245                213.7                 79                9.62   
4246                186.2                 89                8.38   
4247                129.1                104                5.81   
4248                297.5                116               13.39   
4249                154.8                100                6.97   

      total_intl_minutes  total_intl_calls  total_intl_charge  \
0                   13.7                 3               3.70   
1                   12.2                 5               3.29   
2                    6.6                 7               1.78   
3                   10.1                 3               2.73   
4                    7.5                 7               2.03   
...                  ...               ...                ...   
4245                10.3                 6 

In [12]:
train['international_plan']=le.fit_transform(train['international_plan'])

In [13]:
train['voice_mail_plan']=le.fit_transform(train['voice_mail_plan'])

In [14]:
train['churn']=le.fit_transform(train['churn'])

In [15]:
train

state  account_length  area_code  international_plan  voice_mail_plan  \
0        35             107          1                   0                1   
1        31             137          1                   0                0   
2        35              84          0                   1                0   
3        36              75          1                   1                0   
4        19             121          2                   0                1   
...     ...             ...        ...                 ...              ...   
4245     26              83          1                   0                0   
4246     49              73          0                   0                0   
4247     27              75          0                   0                0   
4248     11              50          0                   0                1   
4249     46              86          1                   0                1   

      number_vmail_messages  total_day_minutes  total_day_calls  \
0                        26              161.6              123   
1                         0              243.4              114   
2                         0              299.4               71   
3                         0              166.7              113   
4                        24              218.2               88   
...                     ...                ...              ...   
4245                      0              188.3               70   
4246                      0              177.9               89   
4247                      0              170.7              101   
4248                     40              235.7              127   
4249                     34              129.4              102   

      total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0                27.47              195.5              103             16.62   
1                41.38              121.2              110             10.30   
2                50.90               61.9               88              5.26   
3                28.34              148.3              122             12.61   
4                37.09              348.5              108             29.62   
...                ...                ...              ...               ...   
4245             32.01              243.8               88             20.72   
4246             30.24              131.2               82             11.15   
4247             29.02              193.1              126             16.41   
4248             40.07              223.0              126             18.96   
4249             22.00              267.1              104             22.70   

      total_night_minutes  total_night_calls  total_night_charge  \
0                   254.4                103               11.45   
1                   162.6                104                7.32   
2                   196.9                 89                8.86   
3                   186.9                121                8.41   
4                   212.6                118                9.57   
...                   ...                ...                 ...   
4245                213.7                 79                9.62   
4246                186.2                 89                8.38   
4247                129.1                104                5.81   
4248                297.5                116               13.39   
4249                154.8                100                6.97   

      total_intl_minutes  total_intl_calls  total_intl_charge  \
0                   13.7                 3               3.70   
1                   12.2                 5               3.29   
2                    6.6                 7               1.78   
3                   10.1                 3               2.73   
4                    7.5                 7               2.03   
...                  ...               ...                ...   
4245               

In [16]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   state                          4250 non-null   int32  
 1   account_length                 4250 non-null   int64  
 2   area_code                      4250 non-null   int32  
 3   international_plan             4250 non-null   int32  
 4   voice_mail_plan                4250 non-null   int32  
 5   number_vmail_messages          4250 non-null   int64  
 6   total_day_minutes              4250 non-null   float64
 7   total_day_calls                4250 non-null   int64  
 8   total_day_charge               4250 non-null   float64
 9   total_eve_minutes              4250 non-null   float64
 10  total_eve_calls                4250 non-null   int64  
 11  total_eve_charge               4250 non-null   float64
 12  total_night_minutes            4250 non-null   f

In [17]:
x = train.iloc[:,0:19].values

In [18]:
x.shape

(4250, 19)

In [19]:
y=train.pop('churn').values

In [20]:
y.shape

(4250,)

In [21]:
print(x)

[[ 35.   107.     1.   ...   3.     3.7    1.  ]
 [ 31.   137.     1.   ...   5.     3.29   0.  ]
 [ 35.    84.     0.   ...   7.     1.78   2.  ]
 ...
 [ 27.    75.     0.   ...   7.     1.86   1.  ]
 [ 11.    50.     0.   ...   5.     2.67   2.  ]
 [ 46.    86.     1.   ...  16.     2.51   0.  ]]


In [22]:
print(y)

[0 0 0 ... 0 0 0]


In [23]:
from sklearn.model_selection import train_test_split

In [73]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=4248,random_state=100)

In [74]:
x_train.shape

(4248, 19)

In [75]:
x_train.shape

(4248, 19)

In [76]:
y_train.shape

(4248,)

In [77]:
test['international_plan']=le.fit_transform(test['international_plan'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [78]:
test['voice_mail_plan']=le.fit_transform(test['voice_mail_plan'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [79]:
test["state"]=le.fit_transform(test["state"])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [80]:
test["area_code"]=le.fit_transform(test["area_code"])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [81]:
test

array([[-0.68384451,  0.69956343,  0.00994465, ..., -0.57939381,
        -0.0938701 , -0.42640542],
       [-1.69964217,  0.44765064,  1.41843899, ...,  0.63873795,
        -1.43618025, -1.18894608],
       [-0.95472389, -0.96306101,  0.00994465, ...,  0.63873795,
         1.03367043,  1.86121657],
       ...,
       [ 1.55091034,  1.30415414,  0.00994465, ..., -0.98543773,
         1.6108638 ,  1.09867591],
       [-1.29332311, -0.98825229,  0.00994465, ..., -0.17334989,
         1.20817075, -0.42640542],
       [-1.29332311,  0.22092912,  1.41843899, ...,  0.63873795,
        -0.63079416, -1.18894608]])

In [82]:
test.pop('id')

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [83]:
test

array([[-0.68384451,  0.69956343,  0.00994465, ..., -0.57939381,
        -0.0938701 , -0.42640542],
       [-1.69964217,  0.44765064,  1.41843899, ...,  0.63873795,
        -1.43618025, -1.18894608],
       [-0.95472389, -0.96306101,  0.00994465, ...,  0.63873795,
         1.03367043,  1.86121657],
       ...,
       [ 1.55091034,  1.30415414,  0.00994465, ..., -0.98543773,
         1.6108638 ,  1.09867591],
       [-1.29332311, -0.98825229,  0.00994465, ..., -0.17334989,
         1.20817075, -0.42640542],
       [-1.29332311,  0.22092912,  1.41843899, ...,  0.63873795,
        -0.63079416, -1.18894608]])

In [84]:
test = scalar.transform(test)

In [85]:
from sklearn.linear_model import LogisticRegression 

In [86]:
lor=LogisticRegression()

In [87]:
lor.fit(x_train,y_train)

C:\Users\romil\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [88]:
y_pred=lor.predict(test)

In [89]:
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [90]:
y_trainpred=lor.predict(x_test)

In [91]:
y_trainpred

array([0, 0])

In [92]:
from sklearn.metrics import mean_squared_error,r2_score

In [93]:
score = r2_score(y_test,y_trainpred)

In [94]:
score

-1.0